<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Provincia;
use App\Models\Distrito;

class DistritosSeeder extends Seeder
{
    public function run()
    {
        $distritos = [
            'Bagua' => [
                ['descripcion' => 'Bagua', 'estado' => 1],
                ['descripcion' => 'Aramango', 'estado' => 1],
                ['descripcion' => 'Copallin', 'estado' => 1],
            ],
            'Bongará' => [
                ['descripcion' => 'Jumbilla', 'estado' => 1],
                ['descripcion' => 'Cuispes', 'estado' => 1],
                ['descripcion' => 'Florida', 'estado' => 1],
            ],
            'Chachapoyas' => [
                ['descripcion' => 'Chachapoyas', 'estado' => 1],
                ['descripcion' => 'Huancas', 'estado' => 1],
                ['descripcion' => 'Olleros', 'estado' => 1],
            ],
            'Condorcanqui' => [
                ['descripcion' => 'Nieva', 'estado' => 1],
                ['descripcion' => 'Río Santiago', 'estado' => 1],
                ['descripcion' => 'El Cenepa', 'estado' => 1],
            ],
            'Luya' => [
                ['descripcion' => 'Lamud', 'estado' => 1],
                ['descripcion' => 'Cocabamba', 'estado' => 1],
                ['descripcion' => 'Pisuquia', 'estado' => 1],
            ],
            'Rodríguez de Mendoza' => [
                ['descripcion' => 'San Nicolás', 'estado' => 1],
                ['descripcion' => 'Milpuc', 'estado' => 1],
                ['descripcion' => 'Totora', 'estado' => 1],
            ],
            'Utcubamba' => [
                ['descripcion' => 'Bagua Grande', 'estado' => 1],
                ['descripcion' => 'Cajaruro', 'estado' => 1],
                ['descripcion' => 'Jamalca', 'estado' => 1],
            ],
            'Huaraz' => [
                ['descripcion' => 'Huaraz', 'estado' => 1],
                ['descripcion' => 'Independencia', 'estado' => 1],
                ['descripcion' => 'Taricá', 'estado' => 1],
            ],
            'Carhuaz' => [
                ['descripcion' => 'Carhuaz', 'estado' => 1],
                ['descripcion' => 'Marcara', 'estado' => 1],
                ['descripcion' => 'Pariahuanca', 'estado' => 1],
            ],
            'Aija' => [
                ['descripcion' => 'Aija', 'estado' => 1],
                ['descripcion' => 'Coris', 'estado' => 1],
                ['descripcion' => 'La Merced', 'estado' => 1],
            ],
            'Huari' => [
                ['descripcion' => 'Huari', 'estado' => 1],
                ['descripcion' => 'San Marcos', 'estado' => 1],
                ['descripcion' => 'Rahuapampa', 'estado' => 1],
            ],
            'Asunción' => [
                ['descripcion' => 'Chacas', 'estado' => 1],
                ['descripcion' => 'Acochaca', 'estado' => 1],
                ['descripcion' => 'Chingas', 'estado' => 1],
            ],
            'Casma' => [
                ['descripcion' => 'Casma', 'estado' => 1],
                ['descripcion' => 'Buena Vista Alta', 'estado' => 1],
                ['descripcion' => 'Comandante Noel', 'estado' => 1],
            ],
            'Huaylas' => [
                ['descripcion' => 'Caraz', 'estado' => 1],
                ['descripcion' => 'Santa Cruz', 'estado' => 1],
                ['descripcion' => 'Huallanca', 'estado' => 1],
            ],
            'Pallasca' => [
                ['descripcion' => 'Cabana', 'estado' => 1],
                ['descripcion' => 'Conchucos', 'estado' => 1],
                ['descripcion' => 'Bolognesi', 'estado' => 1],
            ],
            'Pomabamba' => [
                ['descripcion' => 'Pomabamba', 'estado' => 1],
                ['descripcion' => 'Parobamba', 'estado' => 1],
                ['descripcion' => 'Quinuabamba', 'estado' => 1],
            ],
            'Recuay' => [
                ['descripcion' => 'Recuay', 'estado' => 1],
                ['descripcion' => 'Catac', 'estado' => 1],
                ['descripcion' => 'Cotaparaco', 'estado' => 1],
            ],
            'Santa' => [
                ['descripcion' => 'Chimbote', 'estado' => 1],
                ['descripcion' => 'Cáceres del Perú', 'estado' => 1],
                ['descripcion' => 'Moro', 'estado' => 1],
            ],
            'Sihuas' => [
                ['descripcion' => 'Sihuas', 'estado' => 1],
                ['descripcion' => 'Acobamba', 'estado' => 1],
                ['descripcion' => 'Alfonso Ugarte', 'estado' => 1],
            ],
            'Yungay' => [
                ['descripcion' => 'Yungay', 'estado' => 1],
                ['descripcion' => 'Mancos', 'estado' => 1],
                ['descripcion' => 'Ranrahirca', 'estado' => 1],
            ],
            'Abancay' => [
                ['descripcion' => 'Abancay', 'estado' => 1],
                ['descripcion' => 'Tamburco', 'estado' => 1],
                ['descripcion' => 'Chacoche', 'estado' => 1],
            ],
            'Andahuaylas' => [
                ['descripcion' => 'Andahuaylas', 'estado' => 1],
                ['descripcion' => 'San Jerónimo', 'estado' => 1],
                ['descripcion' => 'Talavera', 'estado' => 1],
            ],
            'Antabamba' => [
                ['descripcion' => 'Antabamba', 'estado' => 1],
                ['descripcion' => 'Juan Espinoza Medrano', 'estado' => 1],
                ['descripcion' => 'Sabaino', 'estado' => 1],
            ],
            'Cotabambas' => [
                ['descripcion' => 'Tambobamba', 'estado' => 1],
                ['descripcion' => 'Cotabambas', 'estado' => 1],
                ['descripcion' => 'Mara', 'estado' => 1],
            ],
            'Grau' => [
                ['descripcion' => 'Chuquibambilla', 'estado' => 1],
                ['descripcion' => 'Mamara', 'estado' => 1],
                ['descripcion' => 'Virundo', 'estado' => 1],
            ],
            'Chincheros' => [
                ['descripcion' => 'Chincheros', 'estado' => 1],
                ['descripcion' => 'Ocobamba', 'estado' => 1],
                ['descripcion' => 'Ongoy', 'estado' => 1],
            ],
            'Aymaraes' => [
                ['descripcion' => 'Chalhuanca', 'estado' => 1],
                ['descripcion' => 'Capaya', 'estado' => 1],
                ['descripcion' => 'Colcabamba', 'estado' => 1],
            ],

            'Barranca' => [
        ['descripcion' => 'Barranca', 'estado' => 1],
        ['descripcion' => 'Paramonga', 'estado' => 1],
        ['descripcion' => 'Pativilca', 'estado' => 1],
        ['descripcion' => 'Supe', 'estado' => 1],
        ['descripcion' => 'Supe Puerto', 'estado' => 1],
    ],
    'Cajatambo' => [
        ['descripcion' => 'Cajatambo', 'estado' => 1],
        ['descripcion' => 'Copa', 'estado' => 1],
        ['descripcion' => 'Gorgor', 'estado' => 1],
        ['descripcion' => 'Huancapón', 'estado' => 1],
        ['descripcion' => 'Manás', 'estado' => 1],
    ],
    'Canta' => [
        ['descripcion' => 'Canta', 'estado' => 1],
        ['descripcion' => 'Arahuay', 'estado' => 1],
        ['descripcion' => 'Huamantanga', 'estado' => 1],
        ['descripcion' => 'Huaros', 'estado' => 1],
        ['descripcion' => 'Lachaqui', 'estado' => 1],
        ['descripcion' => 'Lampian', 'estado' => 1],
        ['descripcion' => 'San Buenaventura', 'estado' => 1],
        ['descripcion' => 'Santa Rosa de Quives', 'estado' => 1],
    ],
    'Cañete' => [
        ['descripcion' => 'San Vicente de Cañete', 'estado' => 1],
        ['descripcion' => 'Asia', 'estado' => 1],
        ['descripcion' => 'Calango', 'estado' => 1],
        ['descripcion' => 'Chilca', 'estado' => 1],
        ['descripcion' => 'Coayllo', 'estado' => 1],
        ['descripcion' => 'Imperial', 'estado' => 1],
        ['descripcion' => 'Lunahuaná', 'estado' => 1],
        ['descripcion' => 'Mala', 'estado' => 1],
        ['descripcion' => 'Nuevo Imperial', 'estado' => 1],
        ['descripcion' => 'Pacarán', 'estado' => 1],
        ['descripcion' => 'Quilmana', 'estado' => 1],
        ['descripcion' => 'San Antonio', 'estado' => 1],
        ['descripcion' => 'Santa Cruz de Flores', 'estado' => 1],
        ['descripcion' => 'Zúñiga', 'estado' => 1],
    ],
    'Huaral' => [
        ['descripcion' => 'Huaral', 'estado' => 1],
        ['descripcion' => 'Atavillos Alto', 'estado' => 1],
        ['descripcion' => 'Atavillos Bajo', 'estado' => 1],
        ['descripcion' => 'Aucallama', 'estado' => 1],
        ['descripcion' => 'Chancay', 'estado' => 1],
        ['descripcion' => 'Ihuari', 'estado' => 1],
        ['descripcion' => 'Lampian', 'estado' => 1],
        ['descripcion' => 'Pacaraos', 'estado' => 1],
        ['descripcion' => 'Santa Cruz de Andamarca', 'estado' => 1],
        ['descripcion' => 'Sumbilca', 'estado' => 1],
        ['descripcion' => '27 de Noviembre', 'estado' => 1],
    ],
    'Huarochirí' => [
        ['descripcion' => 'Matucana', 'estado' => 1],
        ['descripcion' => 'Antioquia', 'estado' => 1],
        ['descripcion' => 'Callahuanca', 'estado' => 1],
        ['descripcion' => 'Carampoma', 'estado' => 1],
        ['descripcion' => 'Chicla', 'estado' => 1],
        ['descripcion' => 'Cuenca', 'estado' => 1],
        ['descripcion' => 'Huachupampa', 'estado' => 1],
        ['descripcion' => 'Huanza', 'estado' => 1],
        ['descripcion' => 'Lahuaytambo', 'estado' => 1],
        ['descripcion' => 'Langa', 'estado' => 1],
        ['descripcion' => 'Laraos', 'estado' => 1],
        ['descripcion' => 'Mariatana', 'estado' => 1],
        ['descripcion' => 'Ricardo Palma', 'estado' => 1],
        ['descripcion' => 'San Andrés de Tupicocha', 'estado' => 1],
        ['descripcion' => 'San Antonio (Huarochirí)', 'estado' => 1],
        ['descripcion' => 'San Bartolomé', 'estado' => 1],
        ['descripcion' => 'San Damian', 'estado' => 1],
        ['descripcion' => 'San Juan de Iris', 'estado' => 1],
        ['descripcion' => 'San Juan de Tantaranche', 'estado' => 1],
        ['descripcion' => 'San Lorenzo de Quinti', 'estado' => 1],
        ['descripcion' => 'San Mateo', 'estado' => 1],
        ['descripcion' => 'San Mateo de Otao', 'estado' => 1],
        ['descripcion' => 'San Pedro de Casta', 'estado' => 1],
        ['descripcion' => 'San Pedro de Huancayre', 'estado' => 1],
        ['descripcion' => 'Sangallaya', 'estado' => 1],
        ['descripcion' => 'Santa Cruz de Cocachacra', 'estado' => 1],
        ['descripcion' => 'Santa Eulalia', 'estado' => 1],
        ['descripcion' => 'Santo Domingo de los Olleros', 'estado' => 1],
        ['descripcion' => 'Surco', 'estado' => 1],
    ],
    'Huaura' => [
        ['descripcion' => 'Huacho', 'estado' => 1],
        ['descripcion' => 'Ambar', 'estado' => 1],
        ['descripcion' => 'Caleta de Carquín', 'estado' => 1],
        ['descripcion' => 'Checras', 'estado' => 1],
        ['descripcion' => 'Huaura', 'estado' => 1],
        ['descripcion' => 'Leoncio Prado', 'estado' => 1],
        ['descripcion' => 'Paccho', 'estado' => 1],
        ['descripcion' => 'Santa Leonor', 'estado' => 1],
        ['descripcion' => 'Santa María', 'estado' => 1],
        ['descripcion' => 'Sayán', 'estado' => 1],
        ['descripcion' => 'Végueta', 'estado' => 1],
    ],
    'Lima Metropolitana' => [
        ['descripcion' => 'Lima', 'estado' => 1],
        ['descripcion' => 'Ancón', 'estado' => 1],
        ['descripcion' => 'Ate', 'estado' => 1],
        ['descripcion' => 'Barranco', 'estado' => 1],
        ['descripcion' => 'Breña', 'estado' => 1],
        ['descripcion' => 'Carabayllo', 'estado' => 1],
        ['descripcion' => 'Chaclacayo', 'estado' => 1],
        ['descripcion' => 'Chorrillos', 'estado' => 1],
        ['descripcion' => 'Cieneguilla', 'estado' => 1],
        ['descripcion' => 'Comas', 'estado' => 1],
        ['descripcion' => 'El Agustino', 'estado' => 1],
        ['descripcion' => 'Independencia', 'estado' => 1],
        ['descripcion' => 'Jesús María', 'estado' => 1],
        ['descripcion' => 'La Molina', 'estado' => 1],
        ['descripcion' => 'La Victoria', 'estado' => 1],
        ['descripcion' => 'Lince', 'estado' => 1],
        ['descripcion' => 'Los Olivos', 'estado' => 1],
        ['descripcion' => 'Lurigancho (Chosica)', 'estado' => 1],
        ['descripcion' => 'Lurín', 'estado' => 1],
        ['descripcion' => 'Magdalena del Mar', 'estado' => 1],
        ['descripcion' => 'Miraflores', 'estado' => 1],
        ['descripcion' => 'Pachacámac', 'estado' => 1],
        ['descripcion' => 'Pucusana', 'estado' => 1],
        ['descripcion' => 'Pueblo Libre', 'estado' => 1],
        ['descripcion' => 'Puente Piedra', 'estado' => 1],
        ['descripcion' => 'Punta Hermosa', 'estado' => 1],
        ['descripcion' => 'Punta Negra', 'estado' => 1],
        ['descripcion' => 'Rímac', 'estado' => 1],
        ['descripcion' => 'San Bartolo', 'estado' => 1],
        ['descripcion' => 'San Borja', 'estado' => 1],
        ['descripcion' => 'San Isidro', 'estado' => 1],
        ['descripcion' => 'San Juan de Lurigancho', 'estado' => 1],
        ['descripcion' => 'San Juan de Miraflores', 'estado' => 1],
        ['descripcion' => 'San Luis', 'estado' => 1],
        ['descripcion' => 'San Martín de Porres', 'estado' => 1],
        ['descripcion' => 'San Miguel', 'estado' => 1],
        ['descripcion' => 'Santa Anita', 'estado' => 1],
        ['descripcion' => 'Santa María del Mar', 'estado' => 1],
        ['descripcion' => 'Santa Rosa', 'estado' => 1],
        ['descripcion' => 'Santiago de Surco', 'estado' => 1],
        ['descripcion' => 'Surquillo', 'estado' => 1],
        ['descripcion' => 'Villa El Salvador', 'estado' => 1],
        ['descripcion' => 'Villa María del Triunfo', 'estado' => 1],
    ],
    'Oyón' => [
        ['descripcion' => 'Oyón', 'estado' => 1],
        ['descripcion' => 'Andajes', 'estado' => 1],
        ['descripcion' => 'Caujul', 'estado' => 1],
        ['descripcion' => 'Cochamarca', 'estado' => 1],
        ['descripcion' => 'Naván', 'estado' => 1],
        ['descripcion' => 'Pachangara', 'estado' => 1],
    ],
    'Yauyos' => [
        ['descripcion' => 'Yauyos', 'estado' => 1],
        ['descripcion' => 'Alis', 'estado' => 1],
        ['descripcion' => 'Ayauca', 'estado' => 1],
        ['descripcion' => 'Azángaro', 'estado' => 1],
        ['descripcion' => 'Cacra', 'estado' => 1],
        ['descripcion' => 'Carania', 'estado' => 1],
        ['descripcion' => 'Catahuasi', 'estado' => 1],
        ['descripcion' => 'Chocos', 'estado' => 1],
        ['descripcion' => 'Cochas', 'estado' => 1],
        ['descripcion' => 'Hongos', 'estado' => 1],
        ['descripcion' => 'Huampara', 'estado' => 1],
        ['descripcion' => 'Huancaya', 'estado' => 1],
        ['descripcion' => 'Huangáscar', 'estado' => 1],
        ['descripcion' => 'Huanec', 'estado' => 1],
        ['descripcion' => 'Laraos', 'estado' => 1],
        ['descripcion' => 'Lincha', 'estado' => 1],
        ['descripcion' => 'Madean', 'estado' => 1],
        ['descripcion' => 'Miraflores', 'estado' => 1],
        ['descripcion' => 'Omas', 'estado' => 1],
        ['descripcion' => 'Putinza', 'estado' => 1],
        ['descripcion' => 'Quinches', 'estado' => 1],
        ['descripcion' => 'Quinocay', 'estado' => 1],
        ['descripcion' => 'San Joaquín', 'estado' => 1],
        ['descripcion' => 'San Pedro de Pilas', 'estado' => 1],
        ['descripcion' => 'Tanta', 'estado' => 1],
        ['descripcion' => 'Tauripampa', 'estado' => 1],
        ['descripcion' => 'Tomas', 'estado' => 1],
        ['descripcion' => 'Vitis', 'estado' => 1],
        ['descripcion' => 'Viñac', 'estado' => 1],
        ['descripcion' => 'Huáñec', 'estado' => 1],
    ],
    'Callao' => [
        ['descripcion' => 'Callao', 'estado' => 1],
        ['descripcion' => 'Bellavista', 'estado' => 1],
        ['descripcion' => 'Carmen de la Legua Reynoso', 'estado' => 1],
        ['descripcion' => 'La Perla', 'estado' => 1],
        ['descripcion' => 'La Punta', 'estado' => 1],
        ['descripcion' => 'Ventanilla', 'estado' => 1],
        ['descripcion' => 'Mi Perú', 'estado' => 1],
    ],
        ];
        

        foreach ($distritos as $provinciaDescripcion => $dists) {
            $provincia = Provincia::where('descripcion', $provinciaDescripcion)->first();
            if ($provincia) {
                foreach ($dists as $dist) {
                    $dist['provincia_id'] = $provincia->id;
                    Distrito::create($dist);
                }
            }
        }
    }
}